version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
     - "2181:2181"
    networks:
      - net-sys

  broker:
    image: confluentinc/cp-kafka:7.2.0
    container_name: broker
    ports:
      - "9092:9092"
    expose:
     - "29092"
    depends_on:
      - zookeeper
    env_file: ./cars/modules/broker/config/.env
    networks:
      - net-sys

  payment_system:
    build: ./payment-system/
    image: payment_system
    entrypoint: 
        venv/bin/python start.py
    container_name: payment_system
    environment:
      - MODULE_NAME=payment-system
    ports:
      - 8000:8000
    networks:
      - net-sys
    
  mobile_client:
    build: ./mobile-client/
    image: mobile_client
    entrypoint: 
        venv/bin/python start.py
    container_name: mobile_client
    environment:
      - MODULE_NAME=mobile-client
    ports:
      - 8002:8000
    networks:
      - net-sys
  
  management_system:
    build: ./management-system/
    image: management_system
    entrypoint: 
        venv/bin/python start.py
    container_name: management_system
    environment:
      - MODULE_NAME=management-system
    ports:
      - 8003:8000
    networks:
      - net-sys

  car-monitor:
    build: ./cars/modules/car-monitor
    image: car-monitor
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-monitor
    environment:
      - MODULE_NAME=car-monitor
    volumes:
      - ./cars/shared:/shared
    networks:
      - net-sys

  car-network:
    build: ./cars/modules/car-network
    image: car-network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-network
    environment:
      - MODULE_NAME=car-network
      - MODULE_PORT=8007
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8007:8007"
    networks:
      - net-sys

  car-verify-service:
    build: ./cars/modules/car-verify-service
    image: car-verify-service
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-verify-service
    environment:
      - MODULE_NAME=car-verify-service
      - MODULE_PORT=8008
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8008:8008"
    networks:
      - net-sys

  car-verify-payment:
    build: ./cars/modules/car-verify-payment
    image: car-verify-payment
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-verify-payment
    environment:
      - MODULE_NAME=car-verify-payment
      - MODULE_PORT=8009
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8009:8009"
    networks:
      - net-sys

  car-manager-service:
    build: ./cars/modules/car-manager-service
    image: car-manager-service
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-manager-service
    environment:
      - MODULE_NAME=car-manager-service
      - MODULE_PORT=8010
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8010:8010"
    networks:
      - net-sys

  car-control:
    build: ./cars/modules/car-control
    image: car-control
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-control
    environment:
      - MODULE_NAME=car-control
      - MODULE_PORT=8011
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8011:8011"
    networks:
      - net-sys

  car-verify-geodata:
    build: ./cars/modules/car-verify-geodata
    image: car-verify-geodata
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-verify-geodata
    environment:
      - MODULE_NAME=car-verify-geodata
      - MODULE_PORT=8012
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8012:8012"
    networks:
      - net-sys

  car-data:
    build: ./cars/modules/car-data
    image: car-data
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-data
    environment:
      - MODULE_NAME=car-data
      - MODULE_PORT=8013
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8013:8013"
    networks:
      - net-sys

  car-get-speed-from-geo:
    build: ./cars/modules/car-get-speed-from-geo
    image: car-get-speed-from-geo
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-get-speed-from-geo
    environment:
      - MODULE_NAME=car-get-speed-from-geo
      - MODULE_PORT=8014
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8014:8014"
    networks:
      - net-sys

  car-complex:
    build: ./cars/modules/car-complex
    image: car-complex
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-complex
    environment:
      - MODULE_NAME=car-complex
      - MODULE_PORT=8015
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8015:8015"
    networks:
      - net-sys

  car-gps:
    build: ./cars/modules/car-gps
    image: car-gps
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-gps
    environment:
      - MODULE_NAME=car-gps
      - MODULE_PORT=8016
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8016:8016"
    networks:
      - net-sys

  car-glonass:
    build: ./cars/modules/car-glonass
    image: car-glonass
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-glonass
    environment:
      - MODULE_NAME=car-glonass
      - MODULE_PORT=8017
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8017:8017"
    networks:
      - net-sys

  car-monitoring:
    build: ./cars/modules/car-monitoring
    image: car-monitoring
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-monitoring
    environment:
      - MODULE_NAME=car-monitoring
      - MODULE_PORT=8018
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8018:8018"
    networks:
      - net-sys

  car-engine:
    build: ./cars/modules/car-engine
    image: car-engine
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-engine
    environment:
      - MODULE_NAME=car-engine
      - MODULE_PORT=8019
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8019:8019"
    networks:
      - net-sys

  car-speed-lower:
    build: ./cars/modules/car-speed-lower
    image: car-speed-lower
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-speed-lower
    environment:
      - MODULE_NAME=car-speed-lower
      - MODULE_PORT=8020
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8020:8020"
    networks:
      - net-sys

  car-verify-driver:
    build: ./cars/modules/car-verify-driver
    image: car-verify-driver
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-verify-driver
    environment:
      - MODULE_NAME=car-verify-driver
      - MODULE_PORT=8021
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8021:8021"
    networks:
      - net-sys

  car-camera:
    build: ./cars/modules/car-camera
    image: car-camera
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-camera
    environment:
      - MODULE_NAME=car-camera
      - MODULE_PORT=8022
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8022:8022"
    networks:
      - net-sys

  car-get-speed-from-camera:
    build: ./cars/modules/car-get-speed-from-camera
    image: car-get-speed-from-camera
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-get-speed-from-camera
    environment:
      - MODULE_NAME=car-get-speed-from-camera
      - MODULE_PORT=8023
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8023:8023"
    networks:
      - net-sys

  car-speed-sensors:
    build: ./cars/modules/car-speed-sensors
    image: car-speed-sensors
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-speed-sensors
    environment:
      - MODULE_NAME=car-speed-sensors
      - MODULE_PORT=8024
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8024:8024"
    networks:
      - net-sys

  car-verify-speed:
    build: ./cars/modules/car-verify-speed
    image: car-verify-speed
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-verify-speed
    environment:
      - MODULE_NAME=car-verify-speed
      - MODULE_PORT=8025
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8025:8025"
    networks:
      - net-sys

  car-energy:
    build: ./cars/modules/car-energy
    image: car-energy
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-energy
    environment:
      - MODULE_NAME=car-energy
      - MODULE_PORT=8026
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8026:8026"
    networks:
      - net-sys

  car-skin-sensors:
    build: ./cars/modules/car-skin-sensors
    image: car-skin-sensors
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-skin-sensors
    environment:
      - MODULE_NAME=car-skin-sensors
      - MODULE_PORT=8027
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8027:8027"
    networks:
      - net-sys

  car-adas:
    build: ./cars/modules/car-adas
    image: car-adas
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: car-adas
    environment:
      - MODULE_NAME=car-adas
      - MODULE_PORT=8028
    volumes:
      - ./cars/shared:/shared
    ports:
      - "8028:8028"
    networks:
      - net-sys

networks:
  net-sys:
    driver: bridge